// Static reference data for Yourcipe: default product catalog, default recipes,
// and the fixed category/unit vocabularies used throughout the admin forms.

export const LS_KEYS = {
  products: 'yourcipe_products_v1',
  recipes: 'yourcipe_recipes_v2',
  favorites: 'yourcipe_favorites_v1',
  profile: 'yourcipe_profile_v1',
  darkMode: 'yourcipe_dark_v1',
  weekStartDay: 'yourcipe_week_start_v1',
  vendas: 'yourcipe_vendas_v1',
  hidden: 'yourcipe_hidden_v1',
  sections: 'yourcipe_sections_v1',
  productSections: 'yourcipe_product_sections_v1',
  proteins: 'yourcipe_proteins_v1',
  navRailSide: 'yourcipe_nav_rail_side_v1',
  fontSize: 'yourcipe_font_size_v1',
  // Local presentation preference, shared by guests and signed-in users.
  productLayout: 'yourcipe_product_layout_v1',
  // First-visit-only welcome message (see app.js state init/onSplashContinue).
  // A pure UI preference, never account-linked and never stored server-side.
  welcomeSeen: 'yourcipe_welcome_seen_v1',
};

export const SECTION_DEFS = [
  { key: 'recomendado', label: 'Recomendados' },
  { key: 'pratico', label: 'Práticos para o Dia a Dia' },
  { key: 'ocasiao', label: 'Ocasiões Especiais' },
  { key: 'rapido', label: 'Pronto em 30 Minutos' },
  { key: 'churrasco', label: 'Direto da Churrasqueira' },
  { key: 'petisco', label: 'Petiscos para Compartilhar' },
];

export const PRODUCT_SECTION_DEFS = [
  { key: 'recomendado', label: 'Recomendados' },
  { key: 'promocao', label: 'Promoções' },
];

export const FALLBACK_IMG = 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ycQJDs=';

export const CATEGORIAS_PRODUTO = ['Bovinos', 'Suínos', 'Aves', 'Peixes e Frutos do Mar', 'Linguiças e Embutidos', 'Cortes Especiais', 'Prontos para Comer', 'Padaria', 'Mercearia', 'Hortifruti'];
export const UNIDADES = ['kg', 'un', 'pacote', 'caixa', 'pote'];
export const CATEGORIAS_RECEITA = ['Bovina', 'Suína', 'Ave', 'Peixe', 'Lanches', 'Mista'];
export const DIFICULDADES = ['Fácil', 'Médio', 'Difícil'];

export const DEFAULT_PRODUCTS = [
  { id: 'p1', nome: 'Contra Filé Swift em Bifes 500g', categoria: 'Bovinos', unidade: 'pacote', preco: 34.9, imagem: 'https://images.pexels.com/photos/1927377/pexels-photo-1927377.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p2', nome: 'Cubos de Acém Swift 500g', categoria: 'Bovinos', unidade: 'pacote', preco: 22.9, imagem: 'https://images.pexels.com/photos/1927377/pexels-photo-1927377.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p3', nome: 'Tiras de Alcatra Swift 500g', categoria: 'Bovinos', unidade: 'pacote', preco: 31.9, imagem: 'https://images.pexels.com/photos/1927377/pexels-photo-1927377.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p4', nome: 'Carne Moída de Patinho Swift 500g', categoria: 'Bovinos', unidade: 'pacote', preco: 29.9, imagem: 'https://images.pexels.com/photos/1927377/pexels-photo-1927377.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p5', nome: 'Carne Moída Bolonhesa Swift 500g', categoria: 'Bovinos', unidade: 'pacote', preco: 25.9, imagem: 'https://images.pexels.com/photos/1927377/pexels-photo-1927377.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['promocao'] },
  { id: 'p6', nome: 'Almôndegas Bovinas Swift 500g', categoria: 'Bovinos', unidade: 'pacote', preco: 18.9, imagem: 'https://images.pexels.com/photos/1927377/pexels-photo-1927377.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p7', nome: 'Hambúrguer de Picanha Swift 180g', categoria: 'Bovinos', unidade: 'un', preco: 7.5, imagem: 'https://images.pexels.com/photos/1927377/pexels-photo-1927377.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p8', nome: 'Picanha Swift Legado 1855', categoria: 'Cortes Especiais', unidade: 'kg', preco: 89.9, imagem: 'https://images.pexels.com/photos/2233729/pexels-photo-2233729.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p9', nome: 'Bife de Copa Lombo Suíno Swift 1kg', categoria: 'Suínos', unidade: 'pacote', preco: 29.9, imagem: 'https://images.pexels.com/photos/8845407/pexels-photo-8845407.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p10', nome: 'Lombo Suíno Swift', categoria: 'Suínos', unidade: 'kg', preco: 24.9, imagem: 'https://images.pexels.com/photos/8845407/pexels-photo-8845407.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado', 'promocao'] },
  { id: 'p11', nome: 'Costela Suína Swift', categoria: 'Suínos', unidade: 'kg', preco: 26.9, imagem: 'https://images.pexels.com/photos/8845407/pexels-photo-8845407.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p12', nome: 'Pernil Suíno Swift', categoria: 'Suínos', unidade: 'kg', preco: 22.9, imagem: 'https://images.pexels.com/photos/8845407/pexels-photo-8845407.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p13', nome: 'Bacon Fatiado Swift 250g', categoria: 'Linguiças e Embutidos', unidade: 'pacote', preco: 16.9, imagem: 'https://images.pexels.com/photos/8845354/pexels-photo-8845354.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p14', nome: 'Linguiça Toscana Swift 700g', categoria: 'Linguiças e Embutidos', unidade: 'pacote', preco: 18.9, imagem: 'https://images.pexels.com/photos/8845354/pexels-photo-8845354.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p15', nome: 'Salsicha Hot Dog Swift 500g', categoria: 'Linguiças e Embutidos', unidade: 'pacote', preco: 9.9, imagem: 'https://images.pexels.com/photos/8845354/pexels-photo-8845354.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['promocao'] },
  { id: 'p16', nome: 'Filé de Peito de Frango Swift 1kg', categoria: 'Aves', unidade: 'pacote', preco: 19.9, imagem: 'https://images.pexels.com/photos/616354/pexels-photo-616354.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p17', nome: 'Cubos de Filé de Peito de Frango Swift 1kg', categoria: 'Aves', unidade: 'pacote', preco: 23.9, imagem: 'https://images.pexels.com/photos/616354/pexels-photo-616354.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p18', nome: 'Tiras de Filé de Peito de Frango Swift 1kg', categoria: 'Aves', unidade: 'pacote', preco: 23.9, imagem: 'https://images.pexels.com/photos/616354/pexels-photo-616354.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p19', nome: 'Filé de Coxa e Sobrecoxa Temperado Swift 1kg', categoria: 'Aves', unidade: 'pacote', preco: 22.9, imagem: 'https://images.pexels.com/photos/616354/pexels-photo-616354.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p20', nome: 'Filezinho Sassami Empanado Swift 700g', categoria: 'Aves', unidade: 'pacote', preco: 22.9, imagem: 'https://images.pexels.com/photos/616354/pexels-photo-616354.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado', 'promocao'] },
  { id: 'p21', nome: 'Filé de Tilápia Swift 400g', categoria: 'Peixes e Frutos do Mar', unidade: 'pacote', preco: 22.9, imagem: 'https://images.pexels.com/photos/725991/pexels-photo-725991.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p22', nome: 'Pedaços de Filé de Salmão Swift 500g', categoria: 'Peixes e Frutos do Mar', unidade: 'pacote', preco: 48.9, imagem: 'https://images.pexels.com/photos/725991/pexels-photo-725991.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p23', nome: 'Camarão Pré-cozido Swift 400g', categoria: 'Peixes e Frutos do Mar', unidade: 'pacote', preco: 49.9, imagem: 'https://images.pexels.com/photos/725991/pexels-photo-725991.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p24', nome: 'Filé de Merluza Swift 800g', categoria: 'Peixes e Frutos do Mar', unidade: 'pacote', preco: 34.9, imagem: 'https://images.pexels.com/photos/725991/pexels-photo-725991.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p25', nome: 'Batata Palito Swift 1,5kg', categoria: 'Prontos para Comer', unidade: 'pacote', preco: 19.9, imagem: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['promocao'] },
  { id: 'p26', nome: 'Pão de Alho Baguete Tradicional Swift 400g', categoria: 'Padaria', unidade: 'pacote', preco: 13.9, imagem: 'https://images.pexels.com/photos/1387070/pexels-photo-1387070.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p27', nome: 'Queijo Mussarela Fatiado Swift 300g', categoria: 'Mercearia', unidade: 'pacote', preco: 17.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p28', nome: 'Queijo Sabor Cheddar Fatiado Swift 200g', categoria: 'Mercearia', unidade: 'pacote', preco: 12.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p29', nome: 'Alho Picado Swift 200g', categoria: 'Hortifruti', unidade: 'pote', preco: 13.9, imagem: 'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p30', nome: 'Cebola Picada Swift 300g', categoria: 'Hortifruti', unidade: 'pacote', preco: 6.9, imagem: 'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado', 'promocao'] },
  { id: 'p31', nome: 'Tomate Picado Swift 300g', categoria: 'Hortifruti', unidade: 'pacote', preco: 7.9, imagem: 'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p32', nome: 'Molho Sugo Swift 300g', categoria: 'Mercearia', unidade: 'pote', preco: 6.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p33', nome: 'Mix de Legumes Swift 300g', categoria: 'Hortifruti', unidade: 'pacote', preco: 7.9, imagem: 'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p34', nome: 'Arroz 1kg', categoria: 'Mercearia', unidade: 'pacote', preco: 7.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p35', nome: 'Feijão Preto 1kg', categoria: 'Mercearia', unidade: 'pacote', preco: 9.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['promocao'] },
  { id: 'p36', nome: 'Macarrão Espaguete 500g', categoria: 'Mercearia', unidade: 'pacote', preco: 5.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p37', nome: 'Batata', categoria: 'Hortifruti', unidade: 'kg', preco: 6.99, imagem: 'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p38', nome: 'Cenoura', categoria: 'Hortifruti', unidade: 'kg', preco: 5.99, imagem: 'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p39', nome: 'Pimentão', categoria: 'Hortifruti', unidade: 'kg', preco: 11.99, imagem: 'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p40', nome: 'Limão', categoria: 'Hortifruti', unidade: 'kg', preco: 5.99, imagem: 'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado', 'promocao'] },
  { id: 'p41', nome: 'Alface', categoria: 'Hortifruti', unidade: 'un', preco: 4.99, imagem: 'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p42', nome: 'Mandioca', categoria: 'Hortifruti', unidade: 'kg', preco: 8.99, imagem: 'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p43', nome: 'Creme de Leite 200g', categoria: 'Mercearia', unidade: 'caixa', preco: 4.49, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p44', nome: 'Requeijão 200g', categoria: 'Mercearia', unidade: 'pote', preco: 8.99, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p45', nome: 'Milho Verde 170g', categoria: 'Mercearia', unidade: 'un', preco: 4.29, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['promocao'] },
  { id: 'p46', nome: 'Molho Barbecue 350g', categoria: 'Mercearia', unidade: 'pote', preco: 12.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p47', nome: 'Leite de Coco 200ml', categoria: 'Mercearia', unidade: 'un', preco: 5.49, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p48', nome: 'Farinha de Rosca 500g', categoria: 'Mercearia', unidade: 'pacote', preco: 7.49, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p49', nome: 'Pão de Hambúrguer', categoria: 'Padaria', unidade: 'pacote', preco: 9.9, imagem: 'https://images.pexels.com/photos/1387070/pexels-photo-1387070.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p50', nome: 'Pão de Hot Dog', categoria: 'Padaria', unidade: 'pacote', preco: 8.9, imagem: 'https://images.pexels.com/photos/1387070/pexels-photo-1387070.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado', 'promocao'] },
  { id: 'p51', nome: 'Pão Francês', categoria: 'Padaria', unidade: 'pacote', preco: 7.9, imagem: 'https://images.pexels.com/photos/1387070/pexels-photo-1387070.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p52', nome: 'Batata Palha 120g', categoria: 'Mercearia', unidade: 'pacote', preco: 6.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p53', nome: 'Farofa Pronta 400g', categoria: 'Mercearia', unidade: 'pacote', preco: 8.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p54', nome: 'Queijo Parmesão Ralado 50g', categoria: 'Mercearia', unidade: 'pacote', preco: 6.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p55', nome: 'Leite UHT 1L', categoria: 'Mercearia', unidade: 'caixa', preco: 5.49, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['promocao'] },
  { id: 'p56', nome: 'Manteiga 200g', categoria: 'Mercearia', unidade: 'pote', preco: 11.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p57', nome: 'Ovos com 12 unidades', categoria: 'Mercearia', unidade: 'caixa', preco: 12.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p58', nome: 'Molho Shoyu 150ml', categoria: 'Mercearia', unidade: 'un', preco: 7.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p59', nome: 'Amido de Milho 200g', categoria: 'Mercearia', unidade: 'caixa', preco: 6.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p60', nome: 'Ketchup 400g', categoria: 'Mercearia', unidade: 'pote', preco: 8.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado', 'promocao'] },
  { id: 'p61', nome: 'Mostarda 200g', categoria: 'Mercearia', unidade: 'pote', preco: 5.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
  { id: 'p62', nome: 'Maionese 500g', categoria: 'Mercearia', unidade: 'pote', preco: 9.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: ['recomendado'] },
  { id: 'p63', nome: 'Sal Grosso 1kg', categoria: 'Mercearia', unidade: 'pacote', preco: 7.9, imagem: 'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop', tags: [] },
];

function ing(produtoId, qtd) { return { produtoId, qtd }; }

export const DEFAULT_RECIPES = [
  { id: 'r1', nome: 'Bife Acebolado com Arroz e Fritas', categoria: 'Bovina', tempo: 40, porcoes: 4, dificuldade: 'Fácil', imagem: 'https://images.pexels.com/photos/28503592/pexels-photo-28503592.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['destaque', 'recomendado', 'pratico'],
    ingredientes: [ing('p1', 2), ing('p30', 1), ing('p34', 0.5), ing('p25', 0.5)], extras: ['Sal a gosto', 'Pimenta-do-reino a gosto', 'Óleo para grelhar'],
    modoPreparo: ['Prepare o arroz conforme as instruções da embalagem.', 'Asse ou frite a batata palito até dourar.', 'Tempere os bifes com sal e pimenta.', 'Grelhe os bifes em frigideira bem quente e reserve.', 'Refogue a cebola na mesma frigideira e sirva sobre os bifes.'],
    dicas: ['Não coloque muitos bifes de uma vez para evitar que cozinhem no próprio líquido.'] },
  { id: 'r2', nome: 'Carne de Panela com Batata', categoria: 'Bovina', tempo: 80, porcoes: 6, dificuldade: 'Médio', imagem: 'https://images.pexels.com/photos/30635686/pexels-photo-30635686.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['recomendado', 'ocasiao'],
    ingredientes: [ing('p2', 2), ing('p37', 0.8), ing('p38', 0.3), ing('p30', 1), ing('p29', 0.1), ing('p32', 1)], extras: ['Sal a gosto', 'Pimenta-do-reino a gosto', 'Água quente', 'Cheiro-verde'],
    modoPreparo: ['Sele os cubos de acém em uma panela de pressão.', 'Junte a cebola e o alho e refogue.', 'Acrescente o molho sugo, água quente e os temperos.', 'Cozinhe sob pressão por cerca de 35 minutos.', 'Adicione a batata e a cenoura e cozinhe sem pressão até ficarem macias.'],
    dicas: ['Corte a batata em pedaços grandes para que não desmanche.'] },
  { id: 'r3', nome: 'Estrogonofe de Carne', categoria: 'Bovina', tempo: 35, porcoes: 5, dificuldade: 'Fácil', imagem: 'https://images.pexels.com/photos/1998918/pexels-photo-1998918.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['destaque', 'recomendado', 'pratico', 'rapido'],
    ingredientes: [ing('p3', 2), ing('p43', 2), ing('p30', 1), ing('p32', 0.5), ing('p34', 0.5), ing('p52', 1)], extras: ['Sal a gosto', 'Pimenta-do-reino a gosto', 'Mostarda a gosto', 'Ketchup a gosto'],
    modoPreparo: ['Prepare o arroz.', 'Doure as tiras de alcatra em frigideira bem quente.', 'Adicione a cebola e refogue.', 'Misture o molho sugo, a mostarda e o ketchup.', 'Desligue o fogo, incorpore o creme de leite e sirva com arroz e batata palha.'],
    dicas: ['Adicione o creme de leite com o fogo baixo para evitar que o molho talhe.'] },
  { id: 'r4', nome: 'Escondidinho de Carne Moída', categoria: 'Bovina', tempo: 60, porcoes: 6, dificuldade: 'Médio', imagem: 'https://images.pexels.com/photos/29145751/pexels-photo-29145751.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['recomendado', 'ocasiao'],
    ingredientes: [ing('p4', 2), ing('p42', 1.2), ing('p44', 1), ing('p27', 1), ing('p30', 1), ing('p29', 0.1), ing('p32', 0.5)], extras: ['Sal a gosto', 'Pimenta-do-reino a gosto', 'Cheiro-verde'],
    modoPreparo: ['Cozinhe a mandioca até ficar macia e amasse.', 'Misture o requeijão ao purê de mandioca e ajuste o sal.', 'Refogue a carne moída com cebola e alho.', 'Adicione o molho sugo e cozinhe até reduzir.', 'Monte em um refratário com carne, purê e mussarela.', 'Gratine em forno alto até dourar.'],
    dicas: ['Retire os fios centrais da mandioca antes de amassar.'] },
  { id: 'r5', nome: 'Macarrão à Bolonhesa', categoria: 'Bovina', tempo: 35, porcoes: 5, dificuldade: 'Fácil', imagem: 'https://images.pexels.com/photos/21906876/pexels-photo-21906876.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['pratico', 'rapido', 'recomendado'],
    ingredientes: [ing('p5', 1), ing('p36', 1), ing('p32', 2), ing('p30', 0.5), ing('p54', 1)], extras: ['Sal a gosto', 'Azeite', 'Manjericão ou cheiro-verde'],
    modoPreparo: ['Cozinhe o macarrão em água salgada até ficar al dente.', 'Doure a carne moída e acrescente a cebola.', 'Junte o molho sugo e cozinhe por 10 minutos.', 'Misture o molho ao macarrão ou sirva por cima.', 'Finalize com queijo parmesão.'],
    dicas: ['Reserve um pouco da água do cozimento para ajustar a textura do molho.'] },
  { id: 'r6', nome: 'Almôndegas ao Molho com Purê', categoria: 'Bovina', tempo: 50, porcoes: 5, dificuldade: 'Fácil', imagem: 'https://images.pexels.com/photos/19119681/pexels-photo-19119681.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['recomendado', 'pratico'],
    ingredientes: [ing('p6', 1), ing('p32', 2), ing('p37', 1), ing('p55', 0.3), ing('p56', 0.5), ing('p30', 0.5)], extras: ['Sal a gosto', 'Pimenta-do-reino a gosto', 'Noz-moscada'],
    modoPreparo: ['Cozinhe as batatas e amasse.', 'Misture leite e manteiga ao purê e ajuste os temperos.', 'Doure as almôndegas em uma panela.', 'Acrescente a cebola e o molho sugo.', 'Cozinhe em fogo baixo até as almôndegas ficarem aquecidas e o molho encorpar.', 'Sirva com o purê.'],
    dicas: ['Aqueça o leite antes de misturar ao purê.'] },
  { id: 'r7', nome: 'Picanha na Brasa com Farofa', categoria: 'Bovina', tempo: 55, porcoes: 6, dificuldade: 'Médio', imagem: 'https://images.pexels.com/photos/29724647/pexels-photo-29724647.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['destaque', 'ocasiao', 'churrasco'],
    ingredientes: [ing('p8', 1.3), ing('p63', 0.2), ing('p26', 1), ing('p53', 1)], extras: ['Carvão para churrasqueira', 'Vinagrete para acompanhar'],
    modoPreparo: ['Acenda a churrasqueira e espere formar uma brasa forte sem chamas.', 'Corte a picanha em bifes grossos ou asse a peça inteira.', 'Tempere com sal grosso pouco antes de levar à grelha.', 'Grelhe até o ponto desejado, virando apenas quando estiver bem selada.', 'Deixe a carne descansar e asse o pão de alho.', 'Sirva com farofa.'],
    dicas: ['Fatie a carne contra as fibras para preservar a maciez.'] },
  { id: 'r8', nome: 'Bife de Copa Lombo Acebolado', categoria: 'Suína', tempo: 35, porcoes: 5, dificuldade: 'Fácil', imagem: 'https://images.pexels.com/photos/10267321/pexels-photo-10267321.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['pratico', 'rapido'],
    ingredientes: [ing('p9', 1), ing('p30', 1), ing('p34', 0.5), ing('p40', 0.2)], extras: ['Sal a gosto', 'Pimenta-do-reino a gosto', 'Óleo para grelhar'],
    modoPreparo: ['Prepare o arroz.', 'Tempere os bifes com limão, sal e pimenta.', 'Grelhe os bifes em frigideira quente até dourarem dos dois lados.', 'Refogue a cebola na mesma frigideira.', 'Sirva os bifes com a cebola e o arroz.'],
    dicas: ['Evite cozinhar demais o lombo para não ressecar.'] },
  { id: 'r9', nome: 'Lombo Suíno Assado com Batatas', categoria: 'Suína', tempo: 90, porcoes: 6, dificuldade: 'Médio', imagem: 'https://images.pexels.com/photos/14146069/pexels-photo-14146069.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['ocasiao', 'recomendado'],
    ingredientes: [ing('p10', 1.2), ing('p37', 1), ing('p30', 1), ing('p29', 0.1), ing('p40', 0.2)], extras: ['Sal a gosto', 'Pimenta-do-reino a gosto', 'Alecrim', 'Azeite'],
    modoPreparo: ['Tempere o lombo com alho, limão, sal, pimenta e alecrim.', 'Disponha em uma assadeira com a cebola e cubra com papel-alumínio.', 'Asse por 45 minutos em forno médio.', 'Junte as batatas temperadas e retire o papel-alumínio.', 'Asse até o lombo dourar e as batatas ficarem macias.', 'Descanse a carne antes de fatiar.'],
    dicas: ['Regue o lombo com o caldo da assadeira durante o preparo.'] },
  { id: 'r10', nome: 'Costelinha Suína ao Barbecue', categoria: 'Suína', tempo: 110, porcoes: 5, dificuldade: 'Médio', imagem: 'https://images.pexels.com/photos/37135701/pexels-photo-37135701.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['destaque', 'ocasiao'],
    ingredientes: [ing('p11', 1.5), ing('p46', 1), ing('p37', 1), ing('p29', 0.1)], extras: ['Sal a gosto', 'Pimenta-do-reino a gosto', 'Páprica', 'Azeite'],
    modoPreparo: ['Tempere a costela com alho, sal, pimenta e páprica.', 'Embrulhe em papel-alumínio e asse em forno médio por 70 minutos.', 'Abra o papel, pincele metade do molho barbecue e adicione as batatas.', 'Asse por mais 25 minutos.', 'Pincele o restante do molho e deixe caramelizar.'],
    dicas: ['Asse primeiro coberta para amaciar e finalize descoberta para dourar.'] },
  { id: 'r11', nome: 'Linguiça Toscana Acebolada', categoria: 'Suína', tempo: 25, porcoes: 4, dificuldade: 'Fácil', imagem: 'https://images.pexels.com/photos/38085038/pexels-photo-38085038.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['pratico', 'rapido', 'petisco'],
    ingredientes: [ing('p14', 1), ing('p30', 1), ing('p51', 1)], extras: ['Óleo ou azeite', 'Pimenta-calabresa opcional'],
    modoPreparo: ['Corte a linguiça em rodelas.', 'Doure em frigideira até cozinhar por completo.', 'Acrescente a cebola e refogue até ficar macia.', 'Sirva com pão francês.'],
    dicas: ['Adicione um pequeno volume de água no começo para cozinhar sem queimar e deixe secar para dourar.'] },
  { id: 'r12', nome: 'Feijoada Simples', categoria: 'Suína', tempo: 120, porcoes: 8, dificuldade: 'Médio', imagem: 'https://images.pexels.com/photos/6941026/pexels-photo-6941026.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['destaque', 'ocasiao'],
    ingredientes: [ing('p35', 1), ing('p14', 1), ing('p13', 1), ing('p11', 0.8), ing('p30', 1), ing('p29', 0.15), ing('p53', 1), ing('p34', 0.8)], extras: ['Sal a gosto', 'Folhas de louro', 'Cheiro-verde', 'Laranja para acompanhar'],
    modoPreparo: ['Deixe o feijão de molho e escorra.', 'Doure o bacon, a linguiça e a costela em uma panela grande.', 'Refogue cebola e alho na gordura liberada.', 'Adicione o feijão, o louro e água suficiente.', 'Cozinhe sob pressão até o feijão e as carnes ficarem macios.', 'Acerte o sal e deixe o caldo engrossar.', 'Sirva com arroz e farofa.'],
    dicas: ['Controle o sal somente no final, pois os embutidos já são salgados.'] },
  { id: 'r13', nome: 'Sanduíche de Pernil', categoria: 'Lanches', tempo: 90, porcoes: 6, dificuldade: 'Médio', imagem: 'https://images.pexels.com/photos/34495401/pexels-photo-34495401.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['recomendado', 'ocasiao'],
    ingredientes: [ing('p12', 1.2), ing('p51', 1), ing('p30', 1), ing('p39', 0.3), ing('p32', 1)], extras: ['Sal a gosto', 'Pimenta-do-reino a gosto', 'Cheiro-verde', 'Água quente'],
    modoPreparo: ['Sele o pernil em cubos em uma panela de pressão.', 'Acrescente cebola, pimentão, molho sugo e temperos.', 'Adicione água e cozinhe sob pressão até ficar muito macio.', 'Desfie a carne e reduza o molho.', 'Recheie os pães com o pernil bem quente.'],
    dicas: ['Deixe o recheio úmido, mas sem excesso de líquido para não encharcar o pão.'] },
  { id: 'r14', nome: 'Frango Grelhado com Legumes', categoria: 'Ave', tempo: 30, porcoes: 4, dificuldade: 'Fácil', imagem: 'https://images.pexels.com/photos/36351896/pexels-photo-36351896.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['pratico', 'rapido', 'recomendado'],
    ingredientes: [ing('p16', 1), ing('p33', 2), ing('p40', 0.2)], extras: ['Sal a gosto', 'Pimenta-do-reino a gosto', 'Azeite', 'Ervas secas'],
    modoPreparo: ['Tempere os filés com limão, sal, pimenta e ervas.', 'Grelhe em frigideira quente até dourar e cozinhar por dentro.', 'Salteie o mix de legumes com um fio de azeite.', 'Sirva o frango com os legumes.'],
    dicas: ['Deixe o frango descansar por alguns minutos antes de cortar.'] },
  { id: 'r15', nome: 'Estrogonofe de Frango', categoria: 'Ave', tempo: 35, porcoes: 5, dificuldade: 'Fácil', imagem: 'https://images.pexels.com/photos/18265289/pexels-photo-18265289.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['destaque', 'recomendado', 'pratico', 'rapido'],
    ingredientes: [ing('p17', 1), ing('p43', 2), ing('p30', 1), ing('p32', 0.5), ing('p34', 0.5), ing('p52', 1)], extras: ['Sal a gosto', 'Pimenta-do-reino a gosto', 'Mostarda a gosto', 'Ketchup a gosto'],
    modoPreparo: ['Prepare o arroz.', 'Doure os cubos de frango.', 'Adicione a cebola e refogue.', 'Misture molho sugo, mostarda e ketchup.', 'Desligue o fogo e incorpore o creme de leite.', 'Sirva com arroz e batata palha.'],
    dicas: ['Não cozinhe o creme de leite por muito tempo.'] },
  { id: 'r16', nome: 'Fricassê de Frango', categoria: 'Ave', tempo: 45, porcoes: 6, dificuldade: 'Fácil', imagem: 'https://images.pexels.com/photos/10296266/pexels-photo-10296266.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['recomendado', 'ocasiao'],
    ingredientes: [ing('p17', 1), ing('p44', 1), ing('p43', 1), ing('p45', 1), ing('p27', 1), ing('p52', 1), ing('p30', 0.5)], extras: ['Sal a gosto', 'Pimenta-do-reino a gosto', 'Cheiro-verde'],
    modoPreparo: ['Doure o frango com a cebola e tempere.', 'Bata o milho, o creme de leite e o requeijão até formar um creme.', 'Misture o creme ao frango.', 'Transfira para um refratário e cubra com mussarela.', 'Gratine em forno alto.', 'Finalize com batata palha antes de servir.'],
    dicas: ['Coloque a batata palha somente no final para mantê-la crocante.'] },
  { id: 'r17', nome: 'Coxa e Sobrecoxa Assada com Batatas', categoria: 'Ave', tempo: 75, porcoes: 5, dificuldade: 'Fácil', imagem: 'https://images.pexels.com/photos/4589138/pexels-photo-4589138.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['recomendado', 'ocasiao'],
    ingredientes: [ing('p19', 1), ing('p37', 1), ing('p30', 1), ing('p29', 0.1), ing('p40', 0.2)], extras: ['Pimenta-do-reino a gosto', 'Páprica', 'Azeite'],
    modoPreparo: ['Disponha o frango em uma assadeira.', 'Tempere as batatas com alho, limão, pimenta, páprica e azeite.', 'Distribua as batatas e a cebola ao redor do frango.', 'Asse em forno médio-alto até dourar e cozinhar completamente.'],
    dicas: ['Vire as batatas na metade do tempo para dourarem por igual.'] },
  { id: 'r18', nome: 'Galinhada', categoria: 'Ave', tempo: 60, porcoes: 6, dificuldade: 'Médio', imagem: 'https://images.pexels.com/photos/34442368/pexels-photo-34442368.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['recomendado', 'ocasiao'],
    ingredientes: [ing('p19', 1), ing('p34', 0.6), ing('p30', 1), ing('p29', 0.1), ing('p31', 1), ing('p45', 1)], extras: ['Água quente', 'Colorau ou açafrão-da-terra', 'Cheiro-verde'],
    modoPreparo: ['Doure os pedaços de frango em uma panela grande.', 'Adicione cebola, alho, tomate e colorau.', 'Junte o arroz e refogue por alguns minutos.', 'Acrescente água quente e cozinhe em fogo baixo.', 'Quando o arroz estiver quase pronto, misture o milho.', 'Finalize com cheiro-verde.'],
    dicas: ['Mantenha o fogo baixo após adicionar a água para o arroz cozinhar por igual.'] },
  { id: 'r19', nome: 'Frango Xadrez', categoria: 'Ave', tempo: 35, porcoes: 5, dificuldade: 'Fácil', imagem: 'https://images.pexels.com/photos/29917214/pexels-photo-29917214.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['pratico', 'rapido'],
    ingredientes: [ing('p18', 1), ing('p39', 0.5), ing('p30', 1), ing('p58', 1), ing('p59', 0.2), ing('p34', 0.5)], extras: ['Óleo', 'Gengibre opcional', 'Água'],
    modoPreparo: ['Prepare o arroz.', 'Doure as tiras de frango em fogo alto.', 'Acrescente o pimentão e a cebola e salteie.', 'Misture o shoyu com água e amido.', 'Despeje na panela e cozinhe até o molho engrossar.', 'Sirva com o arroz.'],
    dicas: ['Mantenha os legumes levemente crocantes.'] },
  { id: 'r20', nome: 'Filé de Frango à Parmegiana', categoria: 'Ave', tempo: 50, porcoes: 5, dificuldade: 'Médio', imagem: 'https://images.pexels.com/photos/34902480/pexels-photo-34902480.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['destaque', 'recomendado'],
    ingredientes: [ing('p16', 1), ing('p48', 0.5), ing('p57', 0.25), ing('p32', 2), ing('p27', 1), ing('p34', 0.5)], extras: ['Sal a gosto', 'Pimenta-do-reino a gosto', 'Óleo para fritar ou assar'],
    modoPreparo: ['Tempere os filés.', 'Passe cada filé nos ovos batidos e na farinha de rosca.', 'Frite ou asse até dourar.', 'Cubra com molho sugo e mussarela.', 'Leve ao forno até o queijo derreter.', 'Sirva com arroz.'],
    dicas: ['Para uma versão mais leve, asse os filés sobre uma grade untada.'] },
  { id: 'r21', nome: 'Iscas de Frango Empanadas com Fritas', categoria: 'Ave', tempo: 25, porcoes: 4, dificuldade: 'Fácil', imagem: 'https://images.pexels.com/photos/14950910/pexels-photo-14950910.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['rapido', 'pratico', 'petisco'],
    ingredientes: [ing('p20', 1), ing('p25', 0.5), ing('p60', 0.2), ing('p62', 0.2)], extras: ['Limão para servir'],
    modoPreparo: ['Asse ou prepare as iscas de frango na air fryer até ficarem crocantes.', 'Prepare as batatas até dourarem.', 'Misture ketchup e maionese para um molho rápido.', 'Sirva com limão.'],
    dicas: ['Não sobreponha as iscas na air fryer.'] },
  { id: 'r22', nome: 'Tilápia Grelhada com Arroz e Legumes', categoria: 'Peixe', tempo: 30, porcoes: 4, dificuldade: 'Fácil', imagem: 'https://images.pexels.com/photos/11388099/pexels-photo-11388099.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['pratico', 'rapido', 'recomendado'],
    ingredientes: [ing('p21', 2), ing('p34', 0.5), ing('p33', 1), ing('p40', 0.2)], extras: ['Sal a gosto', 'Pimenta-do-reino a gosto', 'Azeite'],
    modoPreparo: ['Prepare o arroz.', 'Tempere a tilápia com limão, sal e pimenta.', 'Grelhe os filés em frigideira antiaderente.', 'Salteie os legumes com azeite.', 'Sirva imediatamente.'],
    dicas: ['Seque os filés antes de grelhar para obter uma superfície mais dourada.'] },
  { id: 'r23', nome: 'Tilápia Assada com Batatas', categoria: 'Peixe', tempo: 50, porcoes: 5, dificuldade: 'Fácil', imagem: 'https://images.pexels.com/photos/19239119/pexels-photo-19239119.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['recomendado', 'ocasiao'],
    ingredientes: [ing('p21', 2), ing('p37', 0.8), ing('p30', 1), ing('p31', 1), ing('p40', 0.2)], extras: ['Sal a gosto', 'Pimenta-do-reino a gosto', 'Azeite', 'Ervas frescas'],
    modoPreparo: ['Cozinhe as batatas por poucos minutos para pré-amaciar.', 'Monte uma assadeira com batata, cebola e tomate.', 'Tempere a tilápia com limão, sal e pimenta.', 'Coloque os filés sobre os legumes e regue com azeite.', 'Asse até o peixe ficar opaco e macio.'],
    dicas: ['Evite assar demais para a tilápia não ressecar.'] },
  { id: 'r24', nome: 'Salmão ao Forno com Batatas', categoria: 'Peixe', tempo: 40, porcoes: 4, dificuldade: 'Fácil', imagem: 'https://images.pexels.com/photos/5741440/pexels-photo-5741440.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['destaque', 'ocasiao'],
    ingredientes: [ing('p22', 1), ing('p37', 0.8), ing('p40', 0.2), ing('p56', 0.3)], extras: ['Sal a gosto', 'Pimenta-do-reino a gosto', 'Alecrim ou dill'],
    modoPreparo: ['Corte as batatas e cozinhe por alguns minutos.', 'Disponha o salmão e as batatas em uma assadeira.', 'Tempere com limão, sal, pimenta e ervas.', 'Distribua pequenos pedaços de manteiga.', 'Asse até o salmão ficar macio e as batatas douradas.'],
    dicas: ['O centro do salmão deve permanecer úmido.'] },
  { id: 'r25', nome: 'Moqueca de Peixe com Camarão', categoria: 'Peixe', tempo: 55, porcoes: 6, dificuldade: 'Médio', imagem: 'https://images.pexels.com/photos/32252190/pexels-photo-32252190.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['destaque', 'ocasiao'],
    ingredientes: [ing('p24', 1), ing('p23', 1), ing('p31', 2), ing('p30', 1), ing('p39', 0.5), ing('p47', 1), ing('p34', 0.5), ing('p40', 0.2)], extras: ['Sal a gosto', 'Coentro', 'Azeite de dendê opcional'],
    modoPreparo: ['Tempere o peixe com limão e sal.', 'Faça camadas de cebola, tomate, pimentão e peixe em uma panela.', 'Adicione o leite de coco e cozinhe com a panela tampada.', 'Junte o camarão nos minutos finais para não passar do ponto.', 'Finalize com coentro e dendê, se desejar.', 'Sirva com arroz.'],
    dicas: ['Como o camarão é pré-cozido, adicione-o apenas no final.'] },
  { id: 'r26', nome: 'Hot Dog Completo', categoria: 'Lanches', tempo: 25, porcoes: 5, dificuldade: 'Fácil', imagem: 'https://images.pexels.com/photos/36863584/pexels-photo-36863584.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['rapido', 'pratico', 'recomendado'],
    ingredientes: [ing('p15', 1), ing('p50', 1), ing('p32', 1), ing('p30', 0.5), ing('p52', 1), ing('p60', 0.2), ing('p61', 0.2)], extras: ['Sal a gosto', 'Milho ou ervilha opcional'],
    modoPreparo: ['Aqueça as salsichas em água quente.', 'Refogue a cebola e acrescente o molho sugo.', 'Junte as salsichas ao molho e cozinhe por alguns minutos.', 'Monte os pães com salsicha, molho, ketchup e mostarda.', 'Finalize com batata palha.'],
    dicas: ['Não ferva as salsichas por muito tempo para evitar que estourem.'] },
  { id: 'r27', nome: 'Hambúrguer com Cheddar e Fritas', categoria: 'Lanches', tempo: 30, porcoes: 4, dificuldade: 'Fácil', imagem: 'https://images.pexels.com/photos/12325079/pexels-photo-12325079.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['destaque', 'rapido', 'pratico'],
    ingredientes: [ing('p7', 4), ing('p49', 1), ing('p28', 1), ing('p25', 0.5), ing('p30', 0.5), ing('p41', 1), ing('p31', 1), ing('p60', 0.2), ing('p62', 0.2)], extras: ['Sal a gosto', 'Pimenta-do-reino a gosto'],
    modoPreparo: ['Prepare as batatas.', 'Grelhe os hambúrgueres em frigideira bem quente.', 'Coloque o cheddar sobre a carne e tampe para derreter.', 'Toste rapidamente os pães.', 'Monte com maionese, alface, tomate, hambúrguer, cheddar, cebola e ketchup.', 'Sirva com as fritas.'],
    dicas: ['Não pressione o hambúrguer durante o preparo para preservar os sucos.'] },
  { id: 'r28', nome: 'Churrasco Misto Swift', categoria: 'Mista', tempo: 65, porcoes: 8, dificuldade: 'Médio', imagem: 'https://images.pexels.com/photos/37164010/pexels-photo-37164010.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop', tags: ['destaque', 'ocasiao', 'churrasco'],
    ingredientes: [ing('p8', 1.2), ing('p14', 1), ing('p19', 1), ing('p26', 2), ing('p53', 1), ing('p63', 0.2)], extras: ['Carvão para churrasqueira', 'Vinagrete', 'Limão para o frango'],
    modoPreparo: ['Acenda a churrasqueira e aguarde a formação da brasa.', 'Comece pela linguiça e pelo frango, que precisam cozinhar completamente.', 'Tempere a picanha com sal grosso e leve à grelha.', 'Asse os pães de alho nos minutos finais.', 'Fatie as carnes e sirva com farofa e vinagrete.'],
    dicas: ['Use áreas de calor diferente na churrasqueira para controlar o ponto de cada proteína.'] },
];
