import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
const app=fs.readFileSync('app.js','utf8'), template=fs.readFileSync('template.js','utf8'), catalog=fs.readFileSync('catalog.js','utf8'), sql=fs.readFileSync('supabase/032_normalized_catalog_import.sql','utf8');
describe('normalized spreadsheet import',()=>{
 it('downloads and requires six normalized sheets',()=>{for(const name of ['Categorias','Produtos','Receitas','Seções','Receitas por Seção','Produtos por Seção'])expect(app).toContain(name);expect(app).toContain("['receita','proteina'].includes(type)");expect(app).toContain('destaque: true');expect(app).not.toContain("{ tipo: 'secao_receita'");});
 it('validates pages, references, page/entity compatibility and duplicates',()=>{expect(app).toContain("new Set(['home','recipes','products'])");expect(app).toContain('receitas não podem ser vinculadas à página products');expect(app).toContain('produtos não podem ser vinculados à página');expect(app).toContain('seção inexistente');expect(app).toContain('vínculo duplicado');expect(app).toContain('`${page}:${slug}`');});
 it('uses explicit RPC parameters and diagnostics',()=>{for(const p of ['p_sections','p_recipe_section_links','p_product_section_links'])expect(catalog).toContain(p);expect(app).toContain('Nenhuma alteração foi aplicada');});
 it('documents all sheets and shows all counters/modes',()=>{expect(template).toContain('seis abas obrigatórias');expect(template).toContain('categorias classificam conteúdo e não são seções');expect(template).toContain('v.importSectionsCount');expect(template).toContain("['recipeSections', 'Vínculos de receitas'");expect(template).toContain('CustomSelect');});
 it('installs an authorized atomic normalized RPC',()=>{expect(sql).toContain('security definer set search_path');expect(sql).toContain('not public.is_admin()');expect(sql).toContain('catalog_sections');expect(sql).toContain('catalog_section_recipes');expect(sql).toContain('catalog_section_products');expect(sql).toContain('legacy_import_format_not_supported');expect(sql).not.toContain('insert into public.recipe_categories');expect(sql).not.toContain('insert into public.product_categories');expect(sql).toContain('revoke execute');});
});
